### ISSUE TITLE
Arguments to divsufsort()

### ISSUE THREAD

**Issue by tansy** [cielavenir/bzip2#1]
I found you have these mods here (divsufsort and cyclic-sais) and you seem to understand how they work. So I have a question - what is going wrong here in my code.

I tried to use libdivsufsort (from [Yuta Mori's github](https://github.com/y-256/libdivsufsort) but couldn't figure it out as the one in the mod here is somewhat modified)

The one here is version 1.2.1 and `BZ2_blockSort()` looks like this:

```
void divsufsort(const UChar *T, Int32 *SA, Int32 *ftab, Int32 n);

void BZ2_blockSort ( EState* s )
{
   UInt32* ptr    = s->ptr;
   UChar*  block  = s->block;
   UInt32* ftab   = s->ftab;
   Int32   nblock = s->nblock;
   Int32   i;

  block[nblock] = block[0];

/* divsufsort(const UChar *T, Int32 *SA, Int32 *ftab, Int32 n); */
  divsufsort(block, (Int32*)ptr, (Int32*)ftab, nblock);

   s->origPtr = -1;
   for (i = 0; i < s->nblock; i++)
      if (ptr[i] == 0)
         { s->origPtr = i; break; };

   AssertH( s->origPtr != -1, 1003 );
}

```

I tried to imitate this but `divsufsort()` on github (version 2.0.2-1 or 3.0.1, I'm not sure how to interpret this [version file](https://github.com/y-256/libdivsufsort/raw/master/VERSION.cmake)) takes (only) three arguments, and there is only this funcion exported by library anyway.

```
saint_t
divsufsort(const sauchar_t *T, saidx_t *SA, saidx_t n);
```

So I tried to use it "just like that":

```
void BZ2_blockSort ( EState* s )
{
   UInt32* ptr    = s->ptr;
   UChar*  block  = s->block;
   UInt32* ftab   = s->ftab;
   Int32   nblock = s->nblock;
   Int32   i;

  block[nblock] = block[0];

/* divsufsort(const UChar *T, Int32 *SA, Int32 *ftab, Int32 n); */ /* 1.2.1 bzip2-mod */
/* divsufsort(const sauchar_t *T, saidx_t *SA, saidx_t n); */ /* 2.0.2 */
  divsufsort(block, (Int32*)ptr, nblock);

   s->origPtr = -1;
   for (i = 0; i < s->nblock; i++)
      if (ptr[i] == 0)
         { s->origPtr = i; break; };
 
   AssertH( s->origPtr != -1, 1003 );
}
```

But it failed.

It does something but output files are always up to 5kB too short. Quite literally they are always multiple of 5000 bytes and the last part, the last buffer is always missing. I can understand that output buffer in `bzip2.c` is 5000[B] and the last buffer is not written to the stream but why I don't know.

Similarly I tried with [sais](https://sites.google.com/site/yuta256/sais) and [libsais](https://github.com/IlyaGrebnov/libsais) version [1.0.0](https://github.com/IlyaGrebnov/libsais/commit/688ff060d6a2e767d9ff6d62f5f49a12a49150c1) like this:

```
#include "libsais/1.0.0/src/libsais.h"

void BZ2_blockSort ( EState* s )
{
   UInt32* ptr    = s->ptr;
   UChar*  block  = s->block;
   UInt32* ftab   = s->ftab;
   Int32   nblock = s->nblock;
   Int32   i;

  block[nblock] = block[0];

/* int libsais(const unsigned char * T, int * SA, int n); */
  libsais(block, (Int32*)ptr, nblock);

   s->origPtr = -1;
   for (i = 0; i < s->nblock; i++)
      if (ptr[i] == 0)
         { s->origPtr = i; break; };

   AssertH( s->origPtr != -1, 1003 );
}
```

With the same result.

So can you explain in few simple words what are the `divsufsort()` arguments so I can figure out what I did wrong?
For any help thank you in advance.

**Comment by cielavenir** [comment]
I used http://wpage.cocolog-nifty.com/wp/2007/09/bzip2_c99f.html, modified little bit by comparing with https://programtalk.com/vs/?source=elasticsearch-knapsack/src/main/java/org/xbib/io/compress/bzip2/BZip2DivSufSort.java .

He says "customized divsufsort", so maybe original divsufsort is incompatible...

I suggest consulting lbzip2 https://github.com/kjn/lbzip2/blob/master/src/divbwt.c
